### ISSUE TITLE
easy tinkers construct plate mold

### ISSUE THREAD

**Issue by MasterSloth1** [SacrificialFlame/Beyond-The-Void-2-Reborn#10]
*Please check the open and  closed issues before posting an issue!*

#### Issue description:
i see you have made it more difficult to obtain the tinkers construct smeltery plate mold with that being said i found a easy way around it lol using uranium plates and the immersive engineering hammer. after looking further same can be done for pig iron, dark steel, conductive iron, energetic alloy, demon ingot that is all lol. all the materials above i have been able to make with just iron level mesh.

#### Steps to reproduce:
1. craft I.E hammer with uranium ingot (plus others upon further investigation)
2. place crafting result on tinkers smeltery table pour 2 gold ingots smelted over top
3. EZ plate mold

#### Version (make sure you are on the latest version before reporting):
**Other relevant version:** 
beyond the void 2 reborn version 2.9.0

**Comment by SacrificialFlame** [comment]
Fixed
