### ISSUE TITLE
Steadfast Drone and Demonic Will

### ISSUE THREAD

**Issue by cigue1978** [SacrificialFlame/Beyond-The-Void-2-Reborn#11]
*Please check the open and  closed issues before posting an issue!*

#### Issue description:
I cannot finish the quest "Fortress Raid" because the steadfast drone that I got is - for whatever reason - not accepted by the questbook (I have two - one from a mineshaft in the hunting dimension and one actually from the nether - as wanted in the quest - both are not accepted).

Same with the quest "Demonic Will" - I already have several demonic wills with different strength - neither is accepted by the questbook. The questbook does not state that the demonic will needs to have a specific strength so it is assumed that all strengths would be accepted (the blood altar (which is the follow-up quest and needs finishing the quest "Demonic Will") obviously takes a demonic will with any strength - I tested it).

#### Steps to reproduce:
1. For "Fortress Raid": Find a Steadfast Drone in a nether fortress.
2. For "Demonic Will": Obtain one or several demonic wills of various strength. 
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2808
**Mekanism:** 
**Other relevant version:** newest version of modpack

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by SacrificialFlame** [comment]
will have to be fixed next update cause this got posted after I just release the new update

**Comment by cigue1978** [comment]
No problem. I still have other things to do xD.

**Comment by SacrificialFlame** [comment]
I'll have my returning pack dev take a look at it once hes awake

**Comment by cigue1978** [comment]
While you are at this: Could you please take a look at the quest "Sentient Sword Hunts for Demonic Will" where we shall create a sentient sword using an iron sword and a petty tartaric gem. Since the normal iron swords are not craftable, I assumed that the tinkers broadsword should be used for this recipe (like it is used in the industrial foregoing recipes for the machines, i. e. mob crusher and mob slaughter factory.) But this does not work. How do we get the sentient sword then?

**Comment by MasterSloth1** [comment]
@cigue1978 could i get you to press f3 + H then hover over both drones you have and hold shift then take a screen shot of both drone thank you 😄

**Comment by cigue1978** [comment]
Hello MasterSloth1,

sorry for responding so late - but I needed some sleep xD. Down below are the screenshots of both my drones.

![Steadfast Drone 1 - Beyond the Void 2 Reborn](https://user-images.githubusercontent.com/48883043/56091411-df964b00-5eae-11e9-9cb8-ad675eed2ac6.jpg)
![Steadfast Drone 1 2 - Beyond the Void 2 Reborn](https://user-images.githubusercontent.com/48883043/56091412-df964b00-5eae-11e9-9ebe-1f343ef95bbd.jpg)
![Steadfast Drone 2 - Beyond the Void 2 Reborn](https://user-images.githubusercontent.com/48883043/56091413-df964b00-5eae-11e9-91fb-2d600b7c07d0.jpg)
![Steadfast Drone 2 2 - Beyond the Void 2 Reborn](https://user-images.githubusercontent.com/48883043/56091414-e02ee180-5eae-11e9-8ec7-8c24b51ccf78.jpg)

**Comment by MasterSloth1** [comment]
im actually a turkey sorry can u hold down control and shift so i can see the nbt data thanks

**Comment by cigue1978** [comment]
No problem: here are the new screenshots

![Steadfast Drone new1 - Beyond the Void 2 Reborn](https://user-images.githubusercontent.com/48883043/56093270-8b976080-5ec6-11e9-9cbe-38edc4d7d689.jpg)
![Steadfast Drone new2 - Beyond the Void 2 Reborn](https://user-images.githubusercontent.com/48883043/56093271-8b976080-5ec6-11e9-9690-f5c66e7b94a2.jpg)

And thank you for your help.

**Comment by SacrificialFlame** [comment]
We will have this fixed in update 3.3.0 so it gives master sometime to fix it

**Comment by MasterSloth1** [comment]
mkay ive altered the questbook so hopefully it works for you but looking at your images the number at the end of the item name is far different from the one in the questbook so im really not sure how that happened for you either way in the new version that is still yet to be released it should work if it doesnt then you can either cheat in one from jei which will defiantly work or find a new one from the nether
![2019-04-15_18 28 55](https://user-images.githubusercontent.com/34207969/56111528-64b35a00-5fac-11e9-81d4-a9c55f8e6221.png)
![2019-04-15_18 29 00](https://user-images.githubusercontent.com/34207969/56111529-64b35a00-5fac-11e9-94b6-d82912662639.png)

**Comment by MasterSloth1** [comment]
ive have also fixed up the demonic will quest it says to have a will of 1.06 but any strength will work and i have also removed the sentient sword quest as that item is no longer in the pack but will be re added back to the questline when the item gets re-added as collecting will without it will be terrible. (btw i like that idea of the iron broadsword from tinkers being used to make it so it will more than likely be that)

**Comment by cigue1978** [comment]
Thank you for your feedback. I will wait for the update then. 

I am sorry, but another issue just came up: Don't know if it is intentional or not but the enderpearl chicken produces ender shards instead of ender pearls or ender fragments. The ender shards are practically useless other then for one or two recipes for extra utilities while at least the ender fragments can be used to create a stabilized ender pearl which is essentially a substitute for an enderpearl. Is it intended this way (that the enderpearl chicken is practically useless other then for breeding purposes) oder a bug/oversight?
