### ISSUE TITLE
Blue-Screen on Initialization

### ISSUE THREAD

**Issue by salorarainriver** [SacrificialFlame/Beyond-The-Void-2-Reborn#12]
#### Issue description:
This is an unusual sort of bug report, as it relates to a crash of my entire computer and not merely the program itself, but I will try my best to give as much information as I possibly can about what happened. 

I opened the modpack "out of the box", so to speak with no unusual modifications like Optifine or the like, and had installed it via the Twitch client...app...thing? I'm not sure what's the exact terminology, I hope you know what I'm talking about.

In any case, initialization took a very long time (I wasn't timing it, but I would guess 20-40 minutes?), and Google Chrome started buffering and not responding as the game was loading up. The screen also started going dark at moments, and would only turn back on when I moved the mouse. Like it went to screen saver, but way too early.

I should also note that the RAM usage bar was consistently at around 4-5 GB during the entire process. This is concerning because, in my experience, even the larger modpacks would only use around 2 GB on average during initialization, and only occasionally went up to 4 or 5 GB.

And then, finally, I was hit with the infamous Blue Screen. The computer fortunately restarted itself with no further problems, but this was the first time ever that a modpack actually crashed my computer. Normally, it's just Minecraft that crashes, maybe sometimes a Google Chrome page doesn't load fast enough. This is different.

#### Context:
A similarly large modpack, Sevtech Ages, recommends a RAM allocation of 6-8 GBs. Given that I'm only able to allocate 6 GBs to minecraft without putting my computer in danger, I was naturally concerned about performance the first time I booted up that pack. Surprisingly, I was able to play Sevtech with only moderate lagging. During initialization, it eats up around 2 GBs average for the entire period, just like any other modpack.

Given this context, I find it odd that a modpack with similar requirements was so catastrophic for my computer. Please understand that I'm not comparing this experience to that with Sevtech in order to insult you. I'm doing so in the effort of giving as much information as I can about what happened and what my computer is normally capable of handling.

I don't have any idea what the reason for this huge discrepancy was, but if I had to guess, I would say that something in the pack is not particularly RAM-efficient. Not helpful, I know, and it's probably very obvious.

#### Version:

**Beyond the Void 2 version 3.5.0**
**Minecraft version 1.12.2**
**Forge version 14.23.5.2816**

#### Computer Specifications: 
HP Pavilion Gaming Laptop
Windows 10 Home Edition
Intel Core i5-8300H CPU, 2.30 GHz
8 GB of RAM installed 7.89 GB usable
64-bit operating system, x64 based processor
Graphics Cards:
Intel UHD Graphics 630 
NVIDIA GeForce GTX 1050 Ti

#### (Lack of) Crash Log:
I don't really know where in the world I would obtain a crash log when the crash in question was my entire computer. If I am wrong, please tell me so.

**Comment by salorarainriver** [comment]
Additional Note: 

I noticed there was an option in the twitch client to submit a crash log, and figured perhaps this could be a way to bring more information about what happened. However... 

No crash log was found. 

I still don't know where to find the crash logs for Windows 10.

**Comment by SacrificialFlame** [comment]
Most likely a Mod doing the High Ram and that is not on me or the pack as I wont be able to go through every single mod to find the one doing it

**Comment by SacrificialFlame** [comment]
![2019-04-23_15 28 50](https://user-images.githubusercontent.com/48525410/56613578-8b8d1400-65dc-11e9-9665-760f5cc78792.png)

**Comment by SacrificialFlame** [comment]
My Pack dev will comment on this matter later

**Comment by MasterSloth1** [comment]
i noticed your playing on a laptop so first of all can you confirm that you weren't loading the pack with your intel 630 (right click twitch launcher shortcut icon and hover over run with graphics processor then tell me which is default if its your 630 then select 1050 ti) i have run into a similar problem as you with my laptop it loading up games with the default intel card rather than my dedicated card, as for the ram issue there is 320 mods which makes this pack one of the largest on twitch if not the largest so we defiantly recommend allocating 8gb of ram at least and since u only have 8 to use total then im sorry to say even if you do manage to load the pack i cant guarantee it wont be laggy to the max. As you can see flame is using 6gb just loading spawn in once you really get going and make a ton of machines that will shoot up significantly possibly over 10gb as there is a lot of mods to get into, it also depends on how close you make your base, as for the loading times my laptop will take roughly 10-15 min but when its loading on my intel integrated card it will take about 30 to an hour to load so choosing the correct gpu card can make all the difference. so in conclusion your computer is better than mine except ram if you where to upgrade your ram to 16gb or more you could easily run this pack, i think the blue screen was just a coincidence unless its repeatable every time and oh yea make sure your using the latest nvidia stable release and not the beta release. (if i missed one of your questions just message it again thanks) hope this helps and you get things sorted :D.

**Comment by salorarainriver** [comment]
> i noticed your playing on a laptop so first of all can you confirm that you weren't loading the pack with your intel 630 (right click twitch launcher shortcut icon and hover over run with graphics processor then tell me which is default if its your 630 then select 1050 ti)

wait wait wait, how do you do that?

**Comment by salorarainriver** [comment]
I just noticed that you said this pack has 320 mods. 

yeah that... would probably do it, honestly. I was talking it over with someone who's more knowledgable on computers than I am and we agreed that because this happened on startup, that most likely the problem was that there was just a lot of different mods to load and that's how it happened. 

good news is I'm going to the computer store tomorrow to install this memory module that I just got specifically to get more ram, so this will eventually become a moot point for me as I'm gonna end up having 16 ram. 

I still figured it'd be good to report this and see what the problem is, just in case there's a way to make it easier for people with weaker computers. also, that graphics thing... I should really see that I'm using the NVIDIA, anyways. because... I want my shaders, dammit.

(side note, it's nice to hear that my computer's good. I specifically requested a gaming laptop because, well, every other laptop I had always ended up being pretty slow, and I'd put them through absolute hell with my gaming habits, and I figured I'd splurge a bit. All this struggling with lag in Minecraft packs was really getting to me, and I was starting to feel like my machine wasn't that powerful...)

**Comment by MasterSloth1** [comment]
Left click at the blue arrow, then right click the icon in the circle
![image](https://user-images.githubusercontent.com/34207969/56624822-a6b85c00-668e-11e9-9129-d65fd3ae229c.png)
left click at the blue arrow
![image](https://user-images.githubusercontent.com/34207969/56624836-b3d54b00-668e-11e9-8721-afc97a8f6993.png)
at the red mark change that to the 1050 ti then it will use that to open all your programs and not "auto detect" (which is terrible mine always open programs with my intel one) so by forcing it to open with your 1050 it will make all your games run better more than likely.
![image](https://user-images.githubusercontent.com/34207969/56624933-09115c80-668f-11e9-991c-13d0dfd98f7d.png)

**Comment by MasterSloth1** [comment]
also glad to hear your getting more ram that will honestly make your life easier
