### ISSUE TITLE
Tinkers Smeltery Table not longer working - not being able to cast ingots, nuggets and large plates.

### ISSUE THREAD

**Issue by cigue1978** [SacrificialFlame/Beyond-The-Void-2-Reborn#2]
*Please check the open and  closed issues before posting an issue!*

#### Issue description:
Tinkers Construct Smeltery Table suddenly is not working anymore. I can not pull out nuggets, large plates and such. Yesterday - before the new updates - everything functioned normally. What is odd is that Tinkers Smeltery Basin works like normal. How shall I get my coke bricks without being able to get the large plates? 

#### Steps to reproduce:
1. Use any cast (ingot, large plate, nugget or even tool part (tried with axe head)) on the table and try to pull out molten metal (in my case copper). 
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.5.2823
**Mekanism: 1.12.2-1.1.1
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
no crashlog exists for this issue
[gist/pastebin/etc link here]

**Comment by SacrificialFlame** [comment]
Will look into when I get time.

**Comment by SacrificialFlame** [comment]
Anyother modpack dev is having this same problem but looking into it

**Comment by cigue1978** [comment]
Thank you. By the way obviously no new tinkers patterns can created also. So I have some created already like axe head and pickhead - but wanted just a minute ago to make a bowstring - I could not create the respective pattern. Tried all the patterns - none could be created.

**Comment by SacrificialFlame** [comment]
Yea @cigue1978 we know, we were told about it last night and the only thing the other modpack dev came up with is that its on our end somewhere

**Comment by cigue1978** [comment]
Thank you. I will obviously have to wait. xD But it is hard because I really like the challenge of the modpack.

**Comment by SacrificialFlame** [comment]
You can spawn the patterns in that what I am suggesting till I can fix it

**Comment by cigue1978** [comment]
Feels like cheating xD. I will think about it.

**Comment by SacrificialFlame** [comment]
@cigue1978 might have fixed it

**Comment by cigue1978** [comment]
I'll wait for the update then to test it. Thank you for your work.

**Comment by cigue1978** [comment]
Update on twitch is now out. But I cannot upgrade. installation is always stopping and gives info: cannot find addon dependency 263128.
