### ISSUE TITLE
No backups folder

### ISSUE THREAD

**Issue by Enevoado** [SacrificialFlame/Beyond-The-Void-2-Reborn#3]
I was breaking some chance globes and my world crashed and now it crashes everytime I try to open the world again. I just wanted to restore to a previous backup, but couldn't find the backup folder.

**Comment by SacrificialFlame** [comment]
Not a bug, You need to go into ftbbackups.cfg and set the backups yourself as I have no control over where u want the backups to save

**Comment by Enevoado** [comment]
What a pity. Guess I'll copy the ftbbackups.cfg from another modpack and create another world.
Great pack btw. I'm having a lot of fun playing it.
