### ISSUE TITLE
Numismatic Press / Thermal expansion Upgrade kits

### ISSUE THREAD

**Issue by RedR3dReD** [SacrificialFlame/Beyond-The-Void-2-Reborn#6]
*Please check the open and  closed issues before posting an issue!*

#### Steps to reproduce:
1. Looking through Jei
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by SacrificialFlame** [comment]
Not a Bug,  Follow the Quest Book as you get 4 Invar coins under the Early Machinations quest
