### ISSUE TITLE
all the buckets

### ISSUE THREAD

**Issue by MasterSloth1** [SacrificialFlame/Beyond-The-Void-2-Reborn#9]
*Please check the open and  closed issues before posting an issue!*

#### Issue description:
when making sticks using the fresh water recipe it leaves behind a empty bucket in the crafting window when one wasn't used in the recipe

#### Steps to reproduce:
1. fill iron bucket with water
2. place bucket in crafting window to get fresh water
3. make stick recipe using 4 saw dust and one fresh water

#### Version (make sure you are on the latest version before reporting):
**Other relevant version:** 
beyond the void 2 reborn version 2.9.0

**Comment by SacrificialFlame** [comment]
Not a bug that was done on purpose cause people crying about losing said bucket in those stick recipes.
